# Generated by Django 5.0.6 on 2024-07-03 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('descrition', models.TextField(max_length=500)),
            ],
        ),
    ]
