# Generated by Django 5.0.6 on 2024-07-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_category_options_contact_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='id_caregory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='descrition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
